# -*- coding: utf-8 -*-
"""Take Home Test - Data Science.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jneinbO2bhMwfuVY_ZEo7csirlVRE0Gt

#Import Library
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor

"""#Import Data"""

df = pd.read_csv('/content/Food_Delivery_Times.csv')

"""#Data Understanding"""

df.head()

df.describe()

"""#Duplicate"""

df.duplicated().sum()

"""#Missing Values"""

df.isnull().sum()

df['Weather'] = df['Weather'].fillna(df['Weather'].mode()[0])
df['Traffic_Level'] = df['Traffic_Level'].fillna(df['Traffic_Level'].mode()[0])
df['Time_of_Day'] = df['Time_of_Day'].fillna(df['Time_of_Day'].mode()[0])

df['Courier_Experience_yrs'] = df['Courier_Experience_yrs'].fillna(df['Courier_Experience_yrs'].median())
df.isnull().sum()

"""#EDA (Numerik Kontinu)

##Distance KM vs Delivery Time
"""

plt.figure(figsize=(14, 5))
plt.subplot(1, 2, 2)
sns.scatterplot(x='Distance_km', y='Delivery_Time_min', data=df, alpha=0.6, color='darkred')
plt.title('Jarak vs. Waktu Pengiriman')

plt.tight_layout()
plt.show()

"""##Preparation Time vs Delivery Time"""

plt.figure(figsize=(14, 5))
plt.subplot(1, 2, 2)
sns.scatterplot(x='Preparation_Time_min', y='Delivery_Time_min', data=df, alpha=0.6, color='darkgreen')
plt.title('Waktu Persiapan vs. Waktu Pengiriman')

plt.tight_layout()
plt.show()

"""##Courier Experience vs Delivery time"""

plt.figure(figsize=(8, 6))
sns.boxplot(x='Courier_Experience_yrs', y='Delivery_Time_min', data=df, color='gold')
plt.title('Pengalaman Kurir vs. Waktu Pengiriman')
plt.xlabel('Pengalaman Kurir (Tahun)')
plt.ylabel('Waktu Pengiriman (menit)')
plt.xticks(rotation=45)
plt.show()

"""#EDA (Kategorikal)

##Weather
"""

plt.figure(figsize=(10, 6))
sns.boxplot(x='Weather', y='Delivery_Time_min', data=df, palette='Set2')
plt.title('Pengaruh Cuaca pada Waktu Pengiriman')
plt.xlabel('Kondisi Cuaca')
plt.ylabel('Waktu Pengiriman (menit)')
plt.show()

"""##Traffic"""

plt.figure(figsize=(10, 6))
# Urutkan kategori secara logis
traffic_order = ['Low', 'Medium', 'High']
sns.boxplot(x='Traffic_Level', y='Delivery_Time_min', data=df, order=traffic_order, palette='Set1')
plt.title('Pengaruh Tingkat Kemacetan pada Waktu Pengiriman')
plt.xlabel('Tingkat Kemacetan')
plt.ylabel('Waktu Pengiriman (menit)')
plt.show()

"""##Time of The Day"""

plt.figure(figsize=(10, 6))
# Urutkan kategori secara kronologis
time_order = ['Morning', 'Afternoon', 'Evening', 'Night']
sns.boxplot(x='Time_of_Day', y='Delivery_Time_min', data=df, order=time_order, palette='Pastel1')
plt.title('Pengaruh Waktu Hari pada Waktu Pengiriman')
plt.xlabel('Waktu Hari')
plt.ylabel('Waktu Pengiriman (menit)')
plt.show()

"""##Vehicle Type"""

plt.figure(figsize=(10, 6))
sns.boxplot(x='Vehicle_Type', y='Delivery_Time_min', data=df, palette='Dark2')
plt.title('Pengaruh Tipe Kendaraan pada Waktu Pengiriman')
plt.xlabel('Tipe Kendaraan')
plt.ylabel('Waktu Pengiriman (menit)')
plt.show()

"""##Heatmap"""

numerical_cols = ['Distance_km', 'Preparation_Time_min', 'Courier_Experience_yrs', 'Delivery_Time_min']
df_numeric = df[numerical_cols].dropna() # Gunakan dropna untuk keamanan, meskipun sudah di-handle

# Hitung matriks korelasi Pearson
corr_matrix = df_numeric.corr()

sns.set_style("white")

plt.figure(figsize=(8, 7))
sns.heatmap(
    corr_matrix,
    annot=True,
    cmap='viridis',
    fmt=".2f",
    linewidths=.5,
    cbar=True
)
plt.title('Heatmap Matriks Korelasi Variabel Numerik', fontsize=14)
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

"""#Feature Engineering"""

df.drop('Order_ID', axis=1, inplace=True)

categorical_cols = ['Weather', 'Traffic_Level', 'Time_of_Day', 'Vehicle_Type']
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

for col in df.columns:
    if df[col].dtype == 'bool':
        df[col] = df[col].astype(int)

df.head()

"""#Separate fitur and target"""

X = df.drop(columns=['Delivery_Time_min'])
y = df['Delivery_Time_min']

X = X.astype(np.float64)

"""#Multicollinearity test"""

# Tambahkan konstanta (intercept)
X_vif = add_constant(X)

# Hitung VIF
vif_data = pd.DataFrame()
vif_data["Feature"] = X_vif.columns
vif_data["VIF"] = [variance_inflation_factor(X_vif.values, i)
                    for i in range(X_vif.shape[1])]

# Tampilkan Hasil VIF
vif_data = vif_data[vif_data['Feature'] != 'const'].sort_values(by='VIF', ascending=False).reset_index(drop=True)

print("\n--- Hasil Uji Multikolinearitas (VIF) ---")
print(vif_data)

# Jika VIF rendah (seperti hasil sebelumnya), kita lanjutkan.

"""#Train Test Split"""

numerical_cols = ['Distance_km', 'Preparation_Time_min', 'Courier_Experience_yrs']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train[numerical_cols] = scaler.fit_transform(X_train[numerical_cols])

"""#Modelling

##Linear Reggresion
"""

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

coefficients = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
}).sort_values(by="Coefficient", ascending=False)

coefficients

"""##Lasso Reggresion"""

from sklearn.linear_model import Lasso
import pandas as pd

lasso_model = Lasso(alpha=1.0)
lasso_model.fit(X_train, y_train)

lasso_coefficients = pd.DataFrame({
    "Feature": X_train.columns,
    "Coefficient": lasso_model.coef_
}).sort_values(by="Coefficient", ascending=False)

lasso_coefficients

"""##Ridge Reggression"""

from sklearn.linear_model import Ridge
import pandas as pd

ridge_model = Ridge(alpha=1.0)
ridge_model.fit(X_train, y_train)

ridge_coefficients = pd.DataFrame({
    "Feature": X_train.columns,
    "Coefficient": ridge_model.coef_
}).sort_values(by="Coefficient", ascending=False)

ridge_coefficients

"""##Random Forest"""

rf_model = RandomForestRegressor(
    random_state=42,
    n_estimators=100,
    max_depth=10
)
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

rf_model = RandomForestRegressor(random_state=42, n_estimators=100, max_depth=10)
rf_model.fit(X_train, y_train)
feature_importance_df = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': rf_model.feature_importances_
}).sort_values(by='Importance', ascending=False).reset_index(drop=True)

print("\n=== RANDOM FOREST FEATURE IMPORTANCE ===")
print(feature_importance_df)

"""##XGboost"""

xgb_model = XGBRegressor(
    objective='reg:squarederror',
    n_estimators=100,
    learning_rate=0.1,
    random_state=42,
    n_jobs=-1
)
xgb_model.fit(X_train, y_train)
feature_importances = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": xgb_model.feature_importances_
}).sort_values(by="Importance", ascending=False)

# Tampilkan 10 Fitur Terpenting
print("\n=== XGBOOST FEATURE IMPORTANCE (Berdasarkan GAIN) ===")
print(feature_importances.head(10))

"""#Model Evaluation"""

def mean_absolute_percentage_error(y_true, y_pred):
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / (y_true + 1e-10))) * 100

# Fungsi Evaluasi Lengkap
def evaluate_model(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)
    mape = mean_absolute_percentage_error(y_true, y_pred)
    return mae, rmse, r2, mape

models = {
    "1. Linear Regression": LinearRegression(),
    "2. Ridge Regression (Alpha=1.0)": Ridge(alpha=1.0, random_state=42),
    "3. Lasso Regression (Alpha=0.1)": Lasso(alpha=0.1, random_state=42),
    "4. Random Forest Regressor": RandomForestRegressor(random_state=42, n_estimators=100, max_depth=10),
}
if XGBRegressor:
    models["5. XGBoost Regressor"] = XGBRegressor(random_state=42, n_jobs=-1, objective='reg:squarederror', n_estimators=100, learning_rate=0.1)

results = {}
print("\n--- Pelatihan dan Evaluasi Model Komparatif Dimulai ---")

for name, model in models.items():
    print(f"⌛ Melatih {name}...")
    try:
        # Pelatihan
        model.fit(X_train, y_train)

        # Prediksi
        y_pred = model.predict(X_test)

        # Evaluasi
        mae, rmse, r2, mape = evaluate_model(y_test, y_pred)
        results[name] = {"R2 Score": r2, "MAE": mae, "RMSE": rmse, "MAPE (%)": mape}

        print(f"✅ {name} selesai. R2 Score: {r2:.4f}, MAPE: {mape:.2f}%")
    except Exception as e:
        if "XGBRegressor" in name:
            print(f"❌ GAGAL: {name} memerlukan library 'xgboost' yang belum terinstal.")
        else:
            print(f"❌ ERROR saat melatih {name}: {e}")

# Ringkasan Hasil
results_df = pd.DataFrame(results).T
print("\n--- RINGKASAN EVALUASI MODEL AKHIR (Diurutkan berdasarkan R2 Score) ---")
print(results_df.sort_values(by='R2 Score', ascending=False))

